name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt  # Install dependencies from requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src || true  # Prevent breaking on lint issues

    - name: Run Unit Tests
      run: |
        pip install pytest  # Install pytest if not installed already
        pytest -v src  # Run all tests in the 'src' directory with verbose output

    - name: Run Snyk Code Scan
      run: snyk code test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Install Snyk CLI
      run: |
        npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}  # Authenticate with your token

    - name: Run Snyk Code Scan
      run: snyk code test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
