name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 pip-audit

      - name: Lint with flake8
        run: |
          echo "Running lint check..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          pytest

      - name: Dependency vulnerability check (pip-audit)
        run: |
          echo "Running dependency audit..."
          pip-audit

      - name: Build check
        run: |
          echo "Checking build (import test)..."
          python -c "test_app.py"

  snyk-security:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
